[package]
name = "hasty"
version = "0.0.1"
authors = ["russ <rmorris@infocyte.com>"]

[dependencies]
url = "*"
serde = "*"
serde_json = "1.0"
serde_derive = "*"
# webpki = { git = "https://github.com/briansmith/webpki" }
webpki = "*"
mime = "*"
log = "*"

[dependencies.rustls]
# git = "https://github.com/ctz/rustls.git"
version = "0.11.0"
features = ["dangerous_configuration"]